# Generated by Django 2.1.3 on 2018-11-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181110_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(default='Comment', on_delete=django.db.models.deletion.CASCADE, to='posts.Comment'),
        ),
    ]
