# Generated by Django 2.1.3 on 2018-11-19 15:51

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181119_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=tagging.fields.TagField(blank=True, help_text='tag1, tag2, tag3', max_length=255, verbose_name='태그'),
        ),
    ]
