# Generated by Django 2.1.3 on 2018-11-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0003_adapt_max_tag_length'),
        ('posts', '0006_auto_20181121_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categ',
        ),
    ]
