# Generated by Django 2.1.3 on 2018-11-21 15:45

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181121_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categ',
            name='tag',
        ),
        migrations.AddField(
            model_name='categ',
            name='tags',
            field=tagging.fields.TagField(blank=True, help_text='tag1, tag2, tag3', max_length=255, verbose_name='태그'),
        ),
    ]
