# Generated by Django 2.1.3 on 2018-11-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='pub_date',
        ),
    ]
